### PR TITLE
fix(digest): normalize or reject ISO8601 TZ-offset in --since

### LINKED ISSUE #8: [ce-review residual] `--since` lexicographic compare mishandles ISO8601 with TZ offset
**Source**: ce-code-review on PR #7 — `adversarial` finding ADV-003 (conf 90)

### Problem

`scripts/dogfood-digest.sh:168` regex `^[0-9]{4}-[0-9]{2}-[0-9]{2}T` accepts inputs like `2026-04-15T10:00:00+09:00`. The script copies `$window_since` directly into `cutoff_iso` and feeds it to `jq`'s lexicographic `>=` compare against ts strings. Without UTC normalisation, `+` (0x2B) sorts below `Z` (0x5A), so `--since 2026-04-15T10:00:00+09:00` matches events ~9 hours earlier than the user intended.

### Reproduction

```bash
./scripts/dogfood-digest.sh --since '2026-04-15T10:00:00+09:00' --scope local
# returns events whose ts is 2026-04-15T01:00:00Z..., not the intended cutoff
```

The same string-as-time assumption corrupts the sort step at line 246 when JSONL mixes `Z` and `+HH:MM` timestamps.

### Suggested fix

Either reject TZ-offset inputs at the regex layer with an actionable error, or normalise the cutoff via `date -u -d "$window_since" +%Y-%m-%dT%H:%M:%SZ` before storing.

### Why deferred

Pulled out of PR #7 review pass to keep that PR's scope bounded (24-finding remit). Fix touches both BSD/GNU date branches; warrants its own PR with TZ-mixed fixture coverage.

### PR DESCRIPTION
**Pull request by tothefullest08**
## Summary

Closes #8 (ADV-003 from PR #7 ce-code-review, conf 90).

`--since` accepted ISO8601 inputs with a TZ-offset (`+HH:MM`, `-HHMM`) and stored the raw string in `cutoff_iso`. jq's downstream `ts >= cutoff` is a **lexicographic** string compare, where `'+'` (0x2B) sorts below `'Z'` (0x5A). Result: `--since '2026-04-15T10:00:00+09:00'` matched events whose `ts` was `2026-04-15T01:00:00Z`+ — about 9 hours earlier than the user intended. Naive datetimes (no TZ designator at all) had the same hazard.

## Fix

Tighten `scripts/dogfood-digest.sh:188` regex to accept only `YYYY-MM-DDTHH:MM:SSZ` (Z/UTC suffix). Any other ISO8601-looking input with a `T` is rejected with an actionable error pointing at the Z (UTC) form or plain date.

```
dogfood-digest: --since ISO8601 must use Z (UTC) suffix; got non-UTC datetime: 2026-04-15T10:00:00+09:00
  → rewrite as YYYY-MM-DDTHH:MM:SSZ (UTC) or YYYY-MM-DD
```

### Why rejection over `date -u -d` normalisation

Both options are listed in the issue. Chose rejection because:
- `date -u -d` works on GNU but BSD `date -j -f "%Y-%m-%dT%H:%M:%S%z"` doesn't tolerate the `:` in `+09:00` and the format string has to match exactly — pre-stripping the colon for BSD adds maintenance surface.
- Internally `cutoff_iso` is always Z-form (date-only and `Nd` paths already normalise to `T00:00:00Z`). Narrowing the input contract instead of widening the parser keeps the lexicographic-compare invariant unambiguous everywhere downstream.
- Clearer UX: the error tells the user exactly what to type instead of silently shifting their window.

## Scope guard

- `--last`, `--scope`, the `Nd` duration branch, and the date-only branch are untouched. ADV-003 tests assert each is unaffected.
- The sort-step concern noted in the issue body (line 246, mixed-TZ JSONL `ts` strings) is **not** in this PR — internally produced JSONL is always Z-form, and that codepath sits outside the issue title's `--since` scope.

## Test plan

- [x] `bash __tests__/integration/test-dogfood-digest.sh` — ADV-003 block passes (8 new assertions). All prior SC-1~7, ADV-001/002/004/006/007/008 still pass.
- [x] `bash __tests__/integration/test-dogfood-log.sh` — unchanged, still passes.
- [x] DCO sign-off present on the commit.

### ADV-003 coverage

| Input | Before | After |
|-------|--------|-------|
| `2099-01-01T00:00:00+09:00` | silently accepted, wrong window | exit 2, error names Z (UTC) suffix |
| `2099-01-01T00:00:00-08:00` | silently accepted, wrong window | exit 2 |
| `2099-01-01T00:00:00` (naive) | silently accepted, wrong window | exit 2 |
| `2099-01-01T00:00:00Z` | accepted | accepted (regression guard) |
| `2099-01-01` (date-only) | accepted | accepted (regression guard) |
| `7d` (duration) | accepted | accepted (regression guard) |

### CODE REVIEW

File: scripts/dogfood-digest.sh [hunk 1]
```diff
@@ -187,10 +188,20 @@ if [[ "$window_mode" == "since" ]]; then
         fi
     elif [[ "$window_since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
         cutoff_iso="${window_since}T00:00:00Z"
-    elif [[ "$window_since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T ]]; then
+    elif [[ "$window_since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
```
Comment (tothefullest08) [inline scripts/dogfood-digest.sh]: This regex rejects ISO8601 with fractional seconds, e.g. `2026-04-15T10:00:00.123Z` (which `date -u +%Y-%m-%dT%H:%M:%S.%NZ` produces by default on GNU date, and which is what `jq -n now | strftime` round-trips to in some pipelines). That input has `Z` and is unambiguous UTC, so the lex-compare hazard you are guarding against does NOT apply — but it falls through to the next elif at line 193 which then tells the user `must use Z (UTC) suffix`, contradicting the input.

Two reasonable fixes:
1. Widen the regex: `^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$`. Lex compare against second-precision `ts` strings stays safe — `.` (0x2E) < `Z` (0x5A) only widens the cutoff window, never narrows it.
2. If you want to keep the contract second-precision, emit a distinct `fractional seconds not supported` error so the user is not told to do something they already did.

Worth adding a test fixture for `T10:00:00.123Z` either way — it is the most likely user-supplied form.

**Review by tothefullest08 — COMMENTED** [review]
The lex-compare hazard analysis is correct — `+` (0x2B) < `Z` (0x5A) — and rejection-over-normalisation is the right call given the bash 4 + jq + uuidgen + flock runtime constraint (no portable `date -j -f` for BSD without colon-stripping). Two issues I would request changes on, plus one note on the PR description.

1. **The new regex rejects valid Z-form ISO8601 with fractional seconds.** `^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$` does not allow `2026-04-15T10:00:00.123Z`, which is fully valid ISO8601 and IS Z-suffixed. That input has Z and is unambiguous UTC, so the lex-compare hazard does NOT apply — but it falls through to the rejection branch and gets the message "must use Z (UTC) suffix", contradicting the input the user actually typed.

   Callers synthesising timestamps from `$(date -u +%Y-%m-%dT%H:%M:%S.%NZ)` (a common shell idiom on GNU date) would silently fail. Either widen the regex to accept `(\.[0-9]+)?Z` (lex compare against second-precision `ts` strings is still safe — `.` (0x2E) < `Z` (0x5A) widens the cutoff, never narrows it), or — if internal `ts` is guaranteed second-precision — emit a distinct error specifically calling out fractional seconds.

2. **The error message at line 200 misdiagnoses naive datetimes.** `2026-04-15T10:00:00` (no offset, no Z) hits the rejection branch and gets "must use Z (UTC) suffix; got non-UTC datetime". A naive datetime is not "non-UTC" — it has no TZ marker at all. Two failure classes (naive, TZ-offset) are collapsed into one message that accurately describes neither. Splitting them, or rephrasing as "must be `YYYY-MM-DDTHH:MM:SSZ`; got: %s" so the message describes the expected shape rather than imputing intent, would point users at the right fix.

**Minor (PR body, not blocking):** the description says positive-offset cutoffs match events whose ts was "01:00:00Z+ — about 9 hours earlier than the user intended". The actual byte-by-byte lex compare on `+09:00` vs `Z` puts the cutoff *forward* (later) by 9h: only events with `ts >= 10:00:00Z` match, missing the 01:00Z–09:59Z window the user intended. The bug direction is "events 9h LATER than intended are required", not "9h earlier matched". The fix is correct either way, but the PR body steers test rationale and is worth fixing.

File: scripts/dogfood-digest.sh [hunk 2]
```diff
@@ -187,10 +188,20 @@ if [[ "$window_mode" == "since" ]]; then
...
         cutoff_iso="$window_since"
+    elif [[ "$window_since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T ]]; then
+        # Reject TZ-offset (`+HH:MM`, `-0800`, etc.) and naive datetimes.
+        # cutoff_iso feeds jq's lexicographic ts compare, where '+' (0x2B)
+        # sorts below 'Z' (0x5A) — silently shifting the window by hours.
+        # See issue #8 (ADV-003): `--since 2026-04-15T10:00:00+09:00` matched
+        # events ~9h earlier than intended. Force UTC form so the compare is
+        # unambiguous; date-only and Nd inputs are unaffected.
+        printf 'dogfood-digest: --since ISO8601 must use Z (UTC) suffix; got non-UTC datetime: %s\n' "$window_since" >&2
```
Comment (tothefullest08) [inline scripts/dogfood-digest.sh]: The message `must use Z (UTC) suffix; got non-UTC datetime` collapses two distinct failure shapes:

- `2026-04-15T10:00:00+09:00` — has a TZ marker, just not Z. Message is accurate.
- `2026-04-15T10:00:00` — has NO TZ marker at all. Calling this "non-UTC datetime" is misleading; it is "no UTC marker, can't disambiguate".
- `2026-04-15T10:00:00.123Z` — DOES have Z (see comment on line 191). Message is wrong; user reads it and is confused.

Suggest splitting into two distinct error branches, or rephrasing as `must be YYYY-MM-DDTHH:MM:SSZ; got: %s` so the message describes the expected shape rather than imputing intent.

File: __tests__/integration/test-dogfood-digest.sh [hunk 3]
```diff
@@ -168,6 +168,84 @@ else
...
+    faile "ADV-003 TZ-offset rc" "got $tz_rc want 2"
+fi
+if printf '%s' "$tz_stderr" | grep -q 'Z (UTC) suffix'; then
+    pass "--since TZ-offset error names Z (UTC) suffix as the fix"
+else
+    faile "ADV-003 TZ-offset error message" "stderr did not mention Z (UTC) suffix"
+fi
+
+# Negative TZ-offset is the same failure class — must also exit 2.
+set +e
```
Comment (tothefullest08) [inline __tests__/integration/test-dogfood-digest.sh:195]: Missing fixture: `--since 2099-01-01T00:00:00.123Z` (Z-form with fractional seconds). The current regex rejects it, but the rejection error message tells the user to do exactly what they already did. A test pinning the *expected* behavior here (either acceptance after a regex widen, or a distinct error message) would force the contract to be explicit.

File: scripts/dogfood-digest.sh (hunk 1 above)
Comment (tothefullest08) [reply scripts/dogfood-digest.sh]: > This regex rejects ISO8601 with fractional seconds, e.g. `2026-04-15T10:00:00.123Z` (which `date -u +%Y-%m-%dT%H:%M:%S.%NZ` produces by default on GNU date... it falls through to the next elif at line 193 which then tells the user `must use Z (UTC) suffix`, contradicting the input.
> 1. Widen the regex: `^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$`. Lex compare against second-precision `ts` strings stays safe.

Addressed: took option 1 (widen the regex). The accept branch now matches `^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$`. A fixture (`2099-01-01T00:00:00.123Z`) pins acceptance plus rc=0, so a future regex tightening cannot silently regress to the rejection path.

The lex-compare argument is captured in a comment block at the accept branch: `.` (0x2E) sorts below `Z` (0x5A), so a fractional cutoff only *widens* the inclusion window relative to the equivalent second-precision cutoff (more boundary-second events included, never fewer) — no silent shift.

File: scripts/dogfood-digest.sh (hunk 2 above)
Comment (tothefullest08) [reply scripts/dogfood-digest.sh]: > The message `must use Z (UTC) suffix; got non-UTC datetime` collapses two distinct failure shapes... Suggest splitting into two distinct error branches, or rephrasing as `must be YYYY-MM-DDTHH:MM:SSZ; got: %s` so the message describes the expected shape rather than imputing intent.

Addressed: rephrased to `must be YYYY-MM-DDTHH:MM:SSZ (UTC); got: %s` (shape-focused, no intent imputation). Kept the second line `→ rewrite with Z (UTC) suffix, or pass YYYY-MM-DD` as the actionable hint, but the primary line now describes the expected shape so users mapping the error to their input (TZ-offset, naive, etc.) all see the same canonical target shape.

The fractional-Z case from your previous comment is no longer reachable here — it now passes the accept branch. Naive and TZ-offset inputs still land here, but the new message says "must be YYYY-MM-DDTHH:MM:SSZ" instead of imputing "non-UTC datetime", which was the misleading wording for naive input. Pinned with a `grep -q 'must be YYYY-MM-DDTHH:MM:SSZ'` assertion against the TZ-offset stderr so the wording can't drift back.

File: __tests__/integration/test-dogfood-digest.sh (hunk 3 above)
Comment (tothefullest08) [reply __tests__/integration/test-dogfood-digest.sh:195]: > Missing fixture: `--since 2099-01-01T00:00:00.123Z` (Z-form with fractional seconds). The current regex rejects it, but the rejection error message tells the user to do exactly what they already did. A test pinning the *expected* behavior here (either acceptance after a regex widen, or a distinct error message) would force the contract to be explicit.

Addressed with three pinned assertions in the ADV-003 block:
1. `--since '2099-01-01T00:00:00.123Z'` returns 0 events (future cutoff, fractional shape accepted).
2. Same input exits with rc=0 — pins the contract that fractional-Z must NOT take the rejection path.
3. Malformed-TZ input (`+09:00`) emits stderr containing `must be YYYY-MM-DDTHH:MM:SSZ` — pins the new shape-focused error wording (paired with the rephrase from the line-200 thread).

Together these prevent both regressions: regex tightening that silently rejects fractional-Z, and error-message drift that re-introduces the "non-UTC datetime" wording.
