### PR TITLE
fix(digest): prune stale dogfood-digest tempfiles on startup

### LINKED ISSUE #13: [ce-review residual] SIGKILL bypasses EXIT trap, leaks dogfood-digest-raw.* tempfiles
**Source**: ce-code-review on PR #7 — `adversarial` finding ADV-009 (conf 100)

### Problem

`scripts/dogfood-digest.sh:224` (and the analogous renderer trap) registers cleanup on `EXIT INT TERM HUP` after PR #7 merged. `SIGKILL` and OOM-kill remain untrappable by design, leaking `dogfood-digest-raw.XXXXXX` and `.sorted` siblings of size O(JSONL bytes) into `$TMPDIR`.

### Reproduction

```bash
./scripts/dogfood-digest.sh --all --scope local &
PID=$!
sleep 2 && kill -9 $PID
ls /var/folders/*/T/dogfood-digest-raw.* 2>/dev/null
# leftover files persist
```

### Cascade

For long-lived dev / CI environments, every interrupted digest accumulates a tempfile. `/var/folders` (macOS) or `/tmp` (Linux) fills slowly until the next mktemp errors out.

### Suggested fix

Add a startup cleanup pass that prunes stale orphans older than e.g. 1 hour:

```bash
find "${TMPDIR:-/tmp}" -name 'dogfood-digest-raw.*' -mmin +60 -delete 2>/dev/null
```

Same idea in render. The 1-hour window is conservative — far longer than any real digest run.

### Why deferred

Low-impact (cleanup hygiene, not correctness); naturally bundles with other "test-environment polish" work.

### PR DESCRIPTION
**Pull request by tothefullest08**
Closes #13.

## Summary

`scripts/dogfood-digest.sh` and `scripts/dogfood-digest-render.sh` rely on
`trap … EXIT INT TERM HUP` (added in PR #7) to remove their `mktemp`
buffers. SIGKILL and OOM-kill bypass that trap by design, leaking
`dogfood-digest-raw.*` (+ `.sorted` siblings, aggregator) and
`dogfood-digest-in.*` (renderer) into `$TMPDIR`. ADV-009 (conf 100)
flagged the slow accumulation in long-lived dev/CI environments.

This PR adds a best-effort startup prune to both scripts:

```bash
find "${TMPDIR:-/tmp}" -maxdepth 1 -name '<prefix>.*' -mmin +60 -delete 2>/dev/null || true
```

- 60-minute window is far longer than any real digest run.
- `2>/dev/null || true` keeps the prune **best-effort** — a permission
  error or missing `$TMPDIR` must never block a legitimate run.
- `-maxdepth 1` keeps the search shallow (mktemp creates files directly
  in `$TMPDIR`, never in subdirs).
- The aggregator's prune is placed **before** the zero-sources
  fast-path so it still runs on no-input invocations — the most likely
  path right after a SIGKILL'd run.

Existing PR #7 traps remain unchanged (per scope: kept as-is).

## Files

- `scripts/dogfood-digest.sh` — startup prune for `dogfood-digest-raw.*`
- `scripts/dogfood-digest-render.sh` — startup prune for `dogfood-digest-in.*`
- `__tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh` — new
  regression test that plants stale + fresh files in an isolated
  `TMPDIR` and asserts only the >60-min orphans are deleted.

## Test plan

- [x] New test passes:
  ```
  bash __tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh
  → PASS — issue #13 stale-tempfile cleanup
  ```
  All 5 assertions green (3 aggregator + 2 renderer).

- [x] Existing digest suite still passes:
  ```
  bash __tests__/integration/test-dogfood-digest.sh
  → test-dogfood-digest: ALL PASS (SC-1~7 + recursion filter + ADV-006/007/008)
  ```

- [x] Manual SIGKILL repro from the issue still cleans up on next run:
  one stale `dogfood-digest-raw.STALE…` planted, next aggregator run
  removes it (verified by `test-ac-issue13` step 1).

## Guardrails

- bash 4 + jq + uuidgen + flock only — no Python/Node introduced.
- DCO: commit signed off.
- Conventional Commits (`fix:`).
- Scope discipline: existing trap lines untouched (PR #7 territory).

### CODE REVIEW

File: scripts/dogfood-digest.sh [hunk 1]
```diff
@@ -228,6 +228,18 @@ if [[ "$scope" == "global" || "$scope" == "both" ]]; then
...
+# The EXIT/INT/TERM/HUP trap below handles graceful exits, but SIGKILL is
+# untrappable by design — every kill -9 leaks a dogfood-digest-raw.XXXXXX
+# (and its .sorted sibling) of size O(JSONL bytes) into $TMPDIR. Long-lived
+# dev/CI environments accumulate these until mktemp itself errors out.
+# 60-minute window is far longer than any real digest run; -mmin is honoured
+# by both BSD (macOS) and GNU find. Stderr suppression + `|| true` keep the
+# prune best-effort: any pruning failure (permission, missing TMPDIR) must
+# never block a legitimate run. Placed before the zero-sources fast-path so
+# the prune still happens on no-input invocations.
+find "${TMPDIR:-/tmp}" -maxdepth 1 -name 'dogfood-digest-raw.*' -mmin +60 -delete 2>/dev/null || true
```
Comment (tothefullest08) [inline scripts/dogfood-digest.sh]: Placement runs after both scope-resolution blocks (the global block at lines 213–229, and the local block above it). If global glob resolution fails (permissions, malformed `CRUCIBLE_DOGFOOD_HOME`, missing mount), or if the local block panics, the script exits before this prune fires — exactly the edge cases where stale tempfiles are most likely to compound.

Best-effort GC belongs at the top of the script, right after argument parsing and before scope resolution. That path is reachable on every invocation, including malformed-config invocations and arg-error retries after a SIGKILL'd run.

File: scripts/dogfood-digest-render.sh [hunk 2]
```diff
@@ -107,6 +107,15 @@ if ! [[ "$threshold_n" =~ ^[0-9]+$ ]] || [[ "$threshold_n" -le 0 ]]; then
...
 fi
 
+# Best-effort cleanup of stale orphans from prior SIGKILL/OOM-kill runs.
+# The EXIT/INT/TERM/HUP trap below handles graceful exits, but SIGKILL is
+# untrappable by design — every kill -9 leaks a dogfood-digest-in.XXXXXX of
+# size O(JSONL bytes) into $TMPDIR. Long-lived dev/CI environments accumulate
+# these until mktemp itself errors out. 60-minute window is far longer than
+# any real render run; stderr suppression + `|| true` keep the prune
+# best-effort so any pruning failure never blocks a legitimate run.
+find "${TMPDIR:-/tmp}" -maxdepth 1 -name 'dogfood-digest-in.*' -mmin +60 -delete 2>/dev/null || true
```
Comment (tothefullest08) [inline scripts/dogfood-digest-render.sh]: Same placement concern as the aggregator: this prune sits *after* the `--threshold-n` regex validation (line 105). An invalid `--threshold-n` exits 2 before the prune ever runs.

Move the `find` above line 105 (right after argument parsing) so the cleanup is reachable on every invocation, including arg-error paths where users may be retrying after a SIGKILL'd run.

File: __tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+: > "$stale_raw"
+: > "$stale_sorted"
+: > "$fresh_raw"
+
+touch -t "$stamp" "$stale_raw" "$stale_sorted"
+
+TMPDIR="$tmproot" "$aggregator" --all --scope local \
+    --project-root "$tmpproj" --home "$tmphome" >/dev/null 2>&1
+
+if [[ ! -e "$stale_raw" ]]; then
```
Comment (tothefullest08) [inline __tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh:87]: Nice portability work on the mtime stamp (the BSD-vs-GNU date dual-form is exactly right). One missing assertion that would tighten the contract: plant a stale orphan that is *just under* the 60-minute boundary (e.g. 30 min ago) and assert it survives. Right now the test pins `mmin +60` only from the upper side (~120 min planted, must be deleted) and the lower side ($(date) → must survive). A 30-min-old planted file would catch a future regression that flips the find argument to `-mmin -60` (which means the opposite condition) and would still pass the current assertions.

**Review by tothefullest08 — COMMENTED** [review]
The startup-prune approach is correct, the lex-compare reasoning matches BSD/GNU `find` behaviour, and the regression test is excellent (BSD/GNU portable mtime stamping, fresh+stale plant assertions, isolated `TMPDIR` so the user's real `/tmp` never gets touched). Two placement issues I would request changes on, plus a docs gap.

1. **Aggregator prune at line 241 runs after scope resolution.** It is placed deliberately before the zero-sources fast-path — but scope resolution (the global block at lines 213–229 and the local block above it) does its own filesystem `find`/glob calls that can fail or stall on unreadable paths, malformed `CRUCIBLE_DOGFOOD_HOME`, or an unmounted volume. SIGKILL most often happens during the heavy work in the bottom half of the script; if the *next* invocation dies in scope resolution, the prune never fires either, and orphans keep stacking.

   The most reliable place for opportunistic best-effort GC is at the top of the script, immediately after argument parsing and before any I/O. That path is reachable on every invocation, including the malformed-config invocations that are *most* likely to leave tempfiles behind.

2. **Renderer prune at line 117 runs after `--threshold-n` validation.** Same shape, smaller blast radius: an invalid `--threshold-n` exits at line 107 before the prune runs. Move the prune above line 105.

3. **`skills/dogfood-digest/SKILL.md` does not document the cleanup behavior.** We are adding a runtime side effect — silently deleting files in `$TMPDIR` matching `dogfood-digest-*` older than 60 minutes. That belongs in the skill body (or at minimum a HEAD comment in the script), even with the best-effort caveat. Agents/users inspecting tempfiles in the same `$TMPDIR` would be surprised by quiet deletions otherwise.

File: scripts/dogfood-digest.sh (hunk 1 above)
Comment (tothefullest08) [reply scripts/dogfood-digest.sh]: > Best-effort GC belongs at the top of the script, right after argument parsing and before scope resolution.

Addressed: moved the aggregator prune to immediately after the arg-parse `while` loop, before the mutex / `--all` re-assertion / cutoff resolution / scope validation / source resolution blocks. Now reachable on every invocation that gets past argument parsing — including bad `--scope` / bad `--since` / malformed `CRUCIBLE_DOGFOOD_HOME` paths and arg-error retries after a SIGKILL-d run. Updated the comment to call out the new placement reasoning.

File: scripts/dogfood-digest-render.sh (hunk 2 above)
Comment (tothefullest08) [reply scripts/dogfood-digest-render.sh]: > Move the `find` above line 105 (right after argument parsing) so the cleanup is reachable on every invocation, including arg-error paths where users may be retrying after a SIGKILL'd run.

Addressed: moved the renderer prune to immediately after the arg-parse `while` loop, before `--window` / `--scope` / `--threshold-n` validation. Same placement principle as the aggregator — arg-error retries after a SIGKILL-d run now hit the prune.

File: __tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh (hunk 3 above)
Comment (tothefullest08) [reply __tests__/integration/test-ac-issue13-stale-tempfile-cleanup.sh:87]: > plant a stale orphan that is *just under* the 60-minute boundary (e.g. 30 min ago) and assert it survives. Right now the test pins `mmin +60` only from the upper side... A 30-min-old planted file would catch a future regression that flips the find argument to `-mmin -60`.

Addressed: added a 30-min-old planted file (`RECENT30`) for both `dogfood-digest-raw.*` and `dogfood-digest-in.*`. The new assertions explicitly call out that a flip to `-mmin -60` would silently delete files inside the 60-minute window, and the failure message points at that exact regression.

While wiring this up I found a latent issue with the existing `touch -t "$stamp"` form: `touch -t` parses `YYYYMMDDhhmm.SS` in *local* time, but `date -u` produces a UTC representation, so in non-UTC environments (e.g. KST = +9h) the planted mtime silently shifted by the TZ offset. The 120-min upper-bound passed by accident (~11h ago is still > 60 min), but the new 30-min lower-bound exposed it. Switched to `touch -d` with ISO8601 + `Z` so the mtime is interpreted as an absolute UTC instant on both BSD and GNU touch. Tests now pass on both timezones.
